# Generated by Django 3.0.2 on 2020-01-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_auto_20200115_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Year',
        ),
    ]
