# Generated by Django 3.0.2 on 2020-01-15 23:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cellar', '0004_auto_20200115_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Bottle',
        ),
    ]
